import React from 'react'
import App from './app'
import Footer from './footer'
import Head from 'next/head'
function Convert({ children }) {
    return (
        <main>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link
                    rel="preload"
                    href="/fonts/uber/UberMoveBold.otf"
                    as="font"
                    crossOrigin=""
                />
                <link
                    rel="preload"
                    href="/fonts/uber/UberMoveMedium.otf"
                    as="font"
                    crossOrigin=""
                />
            </Head>

            {children}
            <Footer />
        </main>
    )
}

export default Convert