import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Convert from './convert'
export default function Home() {
  return (
    <Convert>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            <a href="https://nextjs.org">FingSpell</a>
          </h1>

          <p className={styles.description}>
            Official  Text to Sign-laguage Translation app
          </p>

          <div className={styles.grid}>
            <Link href="/app">
              <a className={styles.card}>
                <h2>Text to Sign  &rarr;</h2>
                <p>Communication with the deaf by typing text to sign laguage </p>
              </a>
            </Link>

            <a href="https://nextjs.org/learn" className={styles.card}>
              <h2>Learn &rarr;</h2>
              <p>Learn how to work with us to help the deaf societies</p>
            </a>

            <a
              href="https://github.com/vercel/next.js/tree/canary/examples"
              className={styles.card}
            >
              <h2>Examples &rarr;</h2>
              <p>Discover and explore how to use this application.</p>
            </a>

            <a
              href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              className={styles.card}
            >
              <h2>Helping the community &rarr;</h2>
              <p>
                Read on how we aim to support the deaf to help contribute to the societies

              </p>
            </a>
          </div>
        </main>
      </div>
    </Convert>
  )
}
